version: "3"
services:
  api:
    image: "aasousa/api-node-estudo-01"
    ports:
      - "3050:3050"
    links:
      - link-db
  link-db:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
     # - ALLOW_EMPTY_PASSWORD=yes
     # - MONGODB_EXTRA_FLAGS='--wiredTigerCacheSizeGB=2'
      
